version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pooling_db
    environment:
      POSTGRES_DB: pooling_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pooling_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
